title: Soumadeep Saha
email: soumadeep.saha97@gmail.com
description: >-
  Personal website of Soumadeep Saha, a researcher working in Natural Language
  Processing, Deep Learning, AI, etc.
github_username: espressovi
minimal_mistakes_skin: dark
dark_mode: true
search: false
atom_feed:
  hide: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _pages
  - _includes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name   : "Soumadeep Saha"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : |-
    Research Fellow,  
    Indian Statistical Institute,  
    Kolkata
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:soumadeep.saha97@gmail.com"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=RMegz-MAAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/espressovi42"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/espressovi"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/espressovi"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/espressovi"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:soumadeep.saha97@gmail.com"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
